# Generated by Django 4.1.7 on 2023-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=200)),
                ('descrição', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('categoria', models.ManyToManyField(related_name='Animais', to='veterinariapp.categoria')),
            ],
        ),
    ]
